# Generated by Django 2.1.2 on 2020-05-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseinfo',
            name='is_complete',
            field=models.CharField(default='N', max_length=5, verbose_name='是否完成'),
        ),
    ]
