# Generated by Django 2.1.2 on 2020-05-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0003_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='belong_project',
            field=models.CharField(max_length=50, verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='fail_num',
            field=models.CharField(max_length=10),
        ),
    ]
