# Generated by Django 2.1.2 on 2020-05-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0006_auto_20200508_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='project_simple_name',
            field=models.CharField(default='default', max_length=50, verbose_name='项目简称'),
        ),
    ]
