# Generated by Django 2.1.2 on 2020-05-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0007_projectinfo_project_simple_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseinfo',
            name='is_complete',
            field=models.CharField(default='Y', max_length=5, verbose_name='是否完成'),
        ),
    ]
