# Generated by Django 2.0.3 on 2020-05-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0008_auto_20200508_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleinfo',
            name='mode_link',
            field=models.CharField(default='', max_length=200, verbose_name='脑图链接'),
        ),
    ]
