# Generated by Django 2.0.3 on 2020-05-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0010_envinfo_env_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envinfo',
            name='env_name',
            field=models.CharField(max_length=40),
        ),
    ]
