# Generated by Django 2.0.3 on 2020-05-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiManager', '0011_auto_20200511_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envinfo',
            name='belong_project',
        ),
    ]
